export const trackedSpecPriorities: Record<
    string,
    { abilities: string[]; buffs: string[] }
> = {
    "Blood Death Knight": {
        abilities: [
            "Dancing Rune Weapon",
            "Vampiric Blood",
            "Anti-Magic Zone",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
        buffs: [
            "Dancing Rune Weapon",
            "Vampiric Blood",
            "Anti-Magic Zone",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
    },
    "Vengeance Demon Hunter": {
        abilities: [
            "Fiery Brand",
            "Immolation Aura",
            "Fel Devastation",
            "Sigil of Flame",
            "Darkness",
            "Demon Spikes",
        ],
        buffs: [
            "Fiery Brand",
            "Immolation Aura",
            "Fel Devastation",
            "Sigil of Flame",
            "Darkness",
            "Demon Spikes",
        ],
    },
    "Guardian Druid": {
        abilities: [
            "Incarnation: Guardian of Ursoc",
            "Convoke the Spirits",
            "Lunar Beam",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
        buffs: [
            "Incarnation: Guardian of Ursoc",
            "Convoke the Spirits",
            "Lunar Beam",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
    },
    "Brewmaster Monk": {
        abilities: [
            "Invoke Niuzao, the Black Ox",
            "Exploding Keg",
            "Touch of Death",
            "Fortifying Brew",
            "Celestial Infusion",
        ],
        buffs: [
            "Invoke Niuzao, the Black Ox",
            "Exploding Keg",
            "Touch of Death",
            "Fortifying Brew",
            "Celestial Infusion",
        ],
    },
    "Protection Paladin": {
        abilities: [
            "Avenging Wrath",
            "Divine Toll",
            "Ardent Defender",
            "Guardian of Ancient Kings",
            "Divine Shield",
        ],
        buffs: [
            "Avenging Wrath",
            "Divine Toll",
            "Ardent Defender",
            "Guardian of Ancient Kings",
            "Divine Shield",
        ],
    },
    "Protection Warrior": {
        abilities: [
            "Avatar",
            "Ravager",
            "Thunder Blast",
            "Shield Charge",
            "Rend",
            "Shield Wall",
            "Demoralizing Shout",
            "Spell Reflection",
        ],
        buffs: [
            "Avatar",
            "Ravager",
            "Thunder Blast",
            "Shield Charge",
            "Rend",
            "Shield Wall",
            "Demoralizing Shout",
            "Spell Reflection",
        ],
    },
    "Frost Death Knight": {
        abilities: [
            "Pillar of Frost",
            "Frostwyrm's Fury",
            "Breath of Sindragosa",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
        buffs: [
            "Pillar of Frost",
            "Frostwyrm's Fury",
            "Breath of Sindragosa",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
    },
    "Unholy Death Knight": {
        abilities: [
            "Army of the Dead",
            "Raise Abomination",
            "Dark Transformation",
            "Putrefy",
            "Soul Reaper",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
        buffs: [
            "Army of the Dead",
            "Raise Abomination",
            "Dark Transformation",
            "Putrefy",
            "Soul Reaper",
            "Icebound Fortitude",
            "Lichborne",
            "Anti-Magic Shell",
        ],
    },
    "Havoc Demon Hunter": {
        abilities: [
            "Metamorphosis",
            "Eye Beam",
            "Essence Break",
            "The Hunt",
            "Darkness",
        ],
        buffs: [
            "Metamorphosis",
            "Eye Beam",
            "Essence Break",
            "The Hunt",
            "Darkness",
        ],
    },
    "Feral Druid": {
        abilities: [
            "Berserk",
            "Tiger's Fury",
            "Feral Frenzy",
            "Convoke the Spirits",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
        buffs: [
            "Berserk",
            "Tiger's Fury",
            "Feral Frenzy",
            "Convoke the Spirits",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
    },
    "Survival Hunter": {
        abilities: [
            "Aspect of the Eagle",
            "Takedown",
            "Boomstick",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
        buffs: [
            "Aspect of the Eagle",
            "Takedown",
            "Boomstick",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
    },
    "Windwalker Monk": {
        abilities: [
            "Zenith",
            "Touch of Death",
            "Touch of Karma",
            "Fortifying Brew",
        ],
        buffs: [
            "Zenith",
            "Touch of Death",
            "Touch of Karma",
            "Fortifying Brew",
        ],
    },
    "Retribution Paladin": {
        abilities: [
            "Avenging Wrath",
            "Divine Toll",
            "Wake of Ashes",
            "Execution Sentence",
            "Divine Protection",
            "Divine Shield",
        ],
        buffs: [
            "Avenging Wrath",
            "Divine Toll",
            "Wake of Ashes",
            "Execution Sentence",
            "Divine Protection",
            "Divine Shield",
        ],
    },
    "Assassination Rogue": {
        abilities: [
            "Kingsbane",
            "Shiv",
            "Deathmark",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
        buffs: [
            "Kingsbane",
            "Shiv",
            "Deathmark",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
    },
    "Outlaw Rogue": {
        abilities: [
            "Adrenaline Rush",
            "Keep It Rolling",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
        buffs: [
            "Adrenaline Rush",
            "Keep It Rolling",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
    },
    "Subtlety Rogue": {
        abilities: [
            "Shadow Blades",
            "Shadow Dance",
            "Secret Technique",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
        buffs: [
            "Shadow Blades",
            "Shadow Dance",
            "Secret Technique",
            "Vanish",
            "Feint",
            "Evasion",
            "Cloak of Shadows",
            "Crimson Vial",
        ],
    },
    "Enhancement Shaman": {
        abilities: [
            "Sundering",
            "Doom Winds",
            "Primordial Storm",
            "Astral Shift",
        ],
        buffs: [
            "Sundering",
            "Doom Winds",
            "Primordial Storm",
            "Astral Shift",
        ],
    },
    "Arms Warrior": {
        abilities: [
            "Colossus Smash",
            "Ravager",
            "Avatar",
            "Bladestorm",
            "Sweeping Strikes",
            "Execute",
            "Rend",
            "Die by the Sword",
            "Spell Reflection",
            "Defensive Stance",
        ],
        buffs: [
            "Colossus Smash",
            "Ravager",
            "Avatar",
            "Bladestorm",
            "Sweeping Strikes",
            "Execute",
            "Rend",
            "Die by the Sword",
            "Spell Reflection",
            "Defensive Stance",
        ],
    },
    "Fury Warrior": {
        abilities: [
            "Recklessness",
            "Avatar",
            "Odyn's Fury",
            "Bladestorm",
            "Rend",
            "Enraged Regeneration",
            "Spell Reflection",
            "Defensive Stance",
        ],
        buffs: [
            "Recklessness",
            "Avatar",
            "Odyn's Fury",
            "Bladestorm",
            "Rend",
            "Enraged Regeneration",
            "Spell Reflection",
            "Defensive Stance",
        ],
    },
    "Devourer Demon Hunter": {
        abilities: ["Void Metamorphosis", "Collapsing Star", "Darkness"],
        buffs: ["Void Metamorphosis", "Collapsing Star", "Darkness"],
    },
    "Balance Druid": {
        abilities: [
            "Celestial Alignment",
            "Force of Nature",
            "Fury of Elune",
            "Full Moon",
            "Convoke the Spirits",
            "Lunar Eclipse",
            "Solar Eclipse",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
        buffs: [
            "Celestial Alignment",
            "Force of Nature",
            "Fury of Elune",
            "Full Moon",
            "Convoke the Spirits",
            "Lunar Eclipse",
            "Solar Eclipse",
            "Barkskin",
            "Survival Instincts",
            "Frenzied Regeneration",
        ],
    },
    "Augmentation Evoker": {
        abilities: [
            "Ebon Might",
            "Breath of Eons",
            "Time Skip",
            "Spatial Paradox",
            "Time Spiral",
            "Zephyr",
            "Tip the Scales",
            "Obsidian Scales",
        ],
        buffs: [
            "Ebon Might",
            "Breath of Eons",
            "Time Skip",
            "Spatial Paradox",
            "Time Spiral",
            "Zephyr",
            "Tip the Scales",
            "Obsidian Scales",
        ],
    },
    "Devastation Evoker": {
        abilities: [
            "Dragonrage",
            "Deep Breath",
            "Spatial Paradox",
            "Time Spiral",
            "Zephyr",
            "Tip the Scales",
            "Obsidian Scales",
        ],
        buffs: [
            "Dragonrage",
            "Deep Breath",
            "Spatial Paradox",
            "Time Spiral",
            "Zephyr",
            "Tip the Scales",
            "Obsidian Scales",
        ],
    },
    "Beast Mastery Hunter": {
        abilities: [
            "Bestial Wrath",
            "Barbed Shot",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
        buffs: [
            "Bestial Wrath",
            "Barbed Shot",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
    },
    "Marksmanship Hunter": {
        abilities: [
            "Trueshot",
            "Volley",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
        buffs: [
            "Trueshot",
            "Volley",
            "Exhilaration",
            "Survival of the Fittest",
            "Aspect of the Turtle",
        ],
    },
    "Arcane Mage": {
        abilities: [
            "Arcane Surge",
            "Touch of the Magi",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
        buffs: [
            "Arcane Surge",
            "Touch of the Magi",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
    },
    "Fire Mage": {
        abilities: [
            "Combustion",
            "Pyroblast",
            "Fire Blast",
            "Flamestrike",
            "Meteor",
            "Scorch",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
        buffs: [
            "Combustion",
            "Pyroblast",
            "Fire Blast",
            "Flamestrike",
            "Meteor",
            "Scorch",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
    },
    "Frost Mage": {
        abilities: [
            "Ray of Frost",
            "Frozen Orb",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
        buffs: [
            "Ray of Frost",
            "Frozen Orb",
            "Mirror Image",
            "Alter Time",
            "Ice Cold",
        ],
    },
    "Shadow Priest": {
        abilities: [
            "Voidform",
            "Halo",
            "Dispersion",
            "Vampiric Embrace",
            "Desperate Prayer",
            "Fade",
        ],
        buffs: [
            "Voidform",
            "Halo",
            "Dispersion",
            "Vampiric Embrace",
            "Desperate Prayer",
            "Fade",
        ],
    },
    "Elemental Shaman": {
        abilities: [
            "Ascendance",
            "Stormkeeper",
            "Astral Shift",
            "Spiritwalker's Grace",
        ],
        buffs: [
            "Ascendance",
            "Stormkeeper",
            "Astral Shift",
            "Spiritwalker's Grace",
        ],
    },
    "Affliction Warlock": {
        abilities: [
            "Summon Darkglare",
            "Dark Harvest",
            "Unending Resolve",
            "Dark Pact",
        ],
        buffs: [
            "Summon Darkglare",
            "Dark Harvest",
            "Unending Resolve",
            "Dark Pact",
        ],
    },
    "Demonology Warlock": {
        abilities: [
            "Summon Demonic Tyrant",
            "Grimoire: Imp Lord",
            "Grimoire: Fel Ravager",
            "Unending Resolve",
            "Dark Pact",
        ],
        buffs: [
            "Summon Demonic Tyrant",
            "Grimoire: Imp Lord",
            "Grimoire: Fel Ravager",
            "Unending Resolve",
            "Dark Pact",
        ],
    },
    "Destruction Warlock": {
        abilities: [
            "Summon Infernal",
            "Havoc",
            "Unending Resolve",
            "Dark Pact",
        ],
        buffs: [
            "Summon Infernal",
            "Havoc",
            "Unending Resolve",
            "Dark Pact",
        ],
    },
};
